// scripts/pipeline.js — v2 avec Real Trend Scraping
// Orchestrateur : scrape trends → score → generate → polish → publish → commit

const { fetchAllTrends } = require("./fetch-trends");
const { pickBestTrend } = require("./score-trends");
const { generateArticle } = require("./generate-article");
const { writeArticle } = require("./publish");
const { buildBlogIndex } = require("./build-index");
const { execSync } = require("child_process");
const config = require("./config");

async function run() {
  console.log("═══════════════════════════════════════════");
  console.log("  🌴 SUMMER DATING — SEO BUZZ PIPELINE v2");
  console.log("═══════════════════════════════════════════");
  console.log(`  ${new Date().toLocaleString("fr-FR")}`);
  console.log("═══════════════════════════════════════════\n");

  try {
    // === ÉTAPE 1 : Scrape toutes les sources de tendances ===
    const allTrends = await fetchAllTrends();

    if (allTrends.length === 0) {
      console.log("\n⚠️  Aucune tendance trouvée — fallback sur keyword pool");
      return fallbackPipeline();
    }

    // === ÉTAPE 2 : DeepSeek choisit le meilleur sujet ===
    const bestTrend = await pickBestTrend(allTrends);

    // === ÉTAPE 3 : Construire le brief enrichi ===
    const brief = {
      timestamp: new Date().toISOString(),
      hasRealTrend: true,
      articleAngle: bestTrend.articleAngle,
      keywordAngle: {
        category: bestTrend.category,
        primaryKeyword: bestTrend.primaryKeyword,
        secondaryKeyword: bestTrend.secondaryKeywords?.[0] || "",
        allKeywords: [
          bestTrend.primaryKeyword,
          ...(bestTrend.secondaryKeywords || []),
        ],
      },
      trendingContext: [
        {
          title: bestTrend.selectedTrend,
          source: bestTrend.source,
        },
      ],
      suggestedTitle: bestTrend.title,
    };

    // === ÉTAPE 4 : Générer l'article (DeepSeek draft → Claude polish) ===
    const article = await generateArticle(brief);

    // === ÉTAPE 5 : Publier en HTML ===
    const { filePath, slug } = writeArticle(article);

    // === ÉTAPE 6 : Reconstruire l'index blog ===
    buildBlogIndex();

    // === ÉTAPE 7 : Git push (CI only) ===
    if (process.env.CI || process.env.GITHUB_ACTIONS) {
      console.log("\n🚀 Commit & push...");
      try {
        execSync('git config user.name "Summer SEO Bot"');
        execSync('git config user.email "seo-bot@summer.dating"');
        execSync("git add blog/ sitemap.xml");
        execSync(
          `git commit -m "📝 ${article.title}" -m "Source: ${bestTrend.source} | Trend: ${bestTrend.selectedTrend}" -m "Auto-generated by SEO Pipeline v2"`
        );
        execSync("git push");
        console.log("   ✅ Déployé → Vercel auto-deploy");
      } catch (gitErr) {
        console.error("   ⚠️  Git error:", gitErr.message);
      }
    } else {
      console.log("\n💡 Mode local — pas de git push automatique");
      console.log(`   Fichier créé : ${filePath}`);
    }

    console.log("\n═══════════════════════════════════════════");
    console.log("  ✅ PIPELINE v2 TERMINÉ");
    console.log(`  📄 "${article.title}"`);
    console.log(`  🔥 Source: ${bestTrend.source}`);
    console.log(
      `  🔗 ${config.site.url}/blog/${slug}.html`
    );
    console.log("═══════════════════════════════════════════\n");
  } catch (err) {
    console.error("\n❌ ERREUR:", err.message);
    console.error(err.stack);
    process.exit(1);
  }
}

/**
 * Fallback : si aucune tendance n'est trouvée,
 * utiliser le système de keyword pool rotation (v1)
 */
async function fallbackPipeline() {
  const pools = config.keywordPools;
  const categories = Object.keys(pools);
  const dayOfYear = Math.floor(
    (Date.now() - new Date(new Date().getFullYear(), 0, 0)) / 86400000
  );

  const categoryIndex = dayOfYear % categories.length;
  const category = categories[categoryIndex];
  const keywords = pools[category];
  const keywordIndex =
    Math.floor(dayOfYear / categories.length) % keywords.length;
  const primaryKeyword = keywords[keywordIndex];
  const otherCategory = categories[(categoryIndex + 1) % categories.length];
  const secondaryKeyword =
    pools[otherCategory][
      Math.floor(Math.random() * pools[otherCategory].length)
    ];

  console.log(`   📋 Fallback keyword: "${primaryKeyword}" (${category})`);

  const brief = {
    timestamp: new Date().toISOString(),
    hasRealTrend: false,
    articleAngle: `Article SEO evergreen: ${primaryKeyword} — catégorie ${category}`,
    keywordAngle: {
      category,
      primaryKeyword,
      secondaryKeyword,
      allKeywords: [primaryKeyword, secondaryKeyword],
    },
    trendingContext: [],
  };

  const article = await require("./generate-article").generateArticle(brief);
  const { filePath, slug } = writeArticle(article);
  buildBlogIndex();

  if (process.env.CI || process.env.GITHUB_ACTIONS) {
    try {
      execSync('git config user.name "Summer SEO Bot"');
      execSync('git config user.email "seo-bot@summer.dating"');
      execSync("git add blog/ sitemap.xml");
      execSync(
        `git commit -m "📝 ${article.title}" -m "Fallback: keyword pool rotation" -m "Auto-generated by SEO Pipeline v2"`
      );
      execSync("git push");
      console.log("   ✅ Déployé (fallback)");
    } catch (gitErr) {
      console.error("   ⚠️  Git error:", gitErr.message);
    }
  }

  console.log(`\n✅ FALLBACK TERMINÉ : "${article.title}"`);
}

run();
