// scripts/pipeline.js
// Orchestrateur principal : fetch trends → generate → polish → publish → commit

const { buildArticleBrief } = require("./fetch-trends");
const { generateArticle } = require("./generate-article");
const { writeArticle } = require("./publish");
const { buildBlogIndex } = require("./build-index");
const { execSync } = require("child_process");

async function run() {
  console.log("═══════════════════════════════════════════");
  console.log("  🌴 SUMMER DATING — SEO PIPELINE");
  console.log("═══════════════════════════════════════════");
  console.log(`  ${new Date().toLocaleString("fr-FR")}`);
  console.log("═══════════════════════════════════════════\n");

  try {
    // === ÉTAPE 1 : Brief ===
    const brief = await buildArticleBrief();

    // === ÉTAPE 2 : Génération (DeepSeek + Claude) ===
    const article = await generateArticle(brief);

    // === ÉTAPE 3 : Publication HTML ===
    const { filePath, slug } = writeArticle(article);

    // === ÉTAPE 4 : Rebuild index ===
    buildBlogIndex();

    // === ÉTAPE 5 : Git commit + push (si dans CI) ===
    if (process.env.CI || process.env.GITHUB_ACTIONS) {
      console.log("\n🚀 Commit & push vers le repo...");
      try {
        execSync('git config user.name "Summer SEO Bot"');
        execSync('git config user.email "seo-bot@summer-dating.vercel.app"');
        execSync("git add blog/ sitemap.xml");
        execSync(
          `git commit -m "📝 Nouvel article: ${article.title}" -m "Slug: ${slug}" -m "Auto-generated by SEO pipeline"`
        );
        execSync("git push");
        console.log("   ✅ Poussé avec succès → Vercel va déployer automatiquement");
      } catch (gitErr) {
        console.error("   ⚠️  Git push échoué:", gitErr.message);
      }
    } else {
      console.log("\n💡 Mode local — pas de git push automatique");
      console.log(`   Fichier créé : ${filePath}`);
    }

    console.log("\n═══════════════════════════════════════════");
    console.log("  ✅ PIPELINE TERMINÉ AVEC SUCCÈS");
    console.log(`  📄 "${article.title}"`);
    console.log(`  🔗 https://summer-dating.vercel.app/blog/${slug}.html`);
    console.log("═══════════════════════════════════════════\n");
  } catch (err) {
    console.error("\n❌ ERREUR PIPELINE:", err.message);
    console.error(err.stack);
    process.exit(1);
  }
}

run();
